# Generated by Django 3.1.2 on 2020-10-04 11:10

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latlng', django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, unique=True)),
            ],
            options={
                'verbose_name_plural': 'location',
            },
        ),
    ]
